
// This file is auto-generated by scripts/generate-search-index.mjs
// Do not edit this file directly.

export type SearchablePage = {
  title: string;
  href: string;
  keywords: string[];
  icon: string;
};

export const searchData: SearchablePage[] = [
  {
    "title": "Inicio",
    "href": "/",
    "keywords": [
      "home",
      "principal",
      "dashboard",
      "inicio"
    ],
    "icon": "Home"
  },
  {
    "title": "Afiliados",
    "href": "/afiliados",
    "keywords": ["afiliados", "portal", "usuarios", "pacientes"],
    "icon": "Users"
  },
  {
    "title": "Prestadores",
    "href": "/prestadores",
    "keywords": ["prestadores", "ips", "proveedores", "medicos"],
    "icon": "Building"
  },
    {
    "title": "Nosotros",
    "href": "/nosotros",
    "keywords": ["nosotros", "quienes somos", "entidad", "informacion"],
    "icon": "Info"
  },
  {
    "title": "Régimen Subsidiado",
    "href": "/afiliados/subsidiado",
    "keywords": ["subsidiado", "afiliacion", "servicios", "salud"],
    "icon": "HeartHandshake"
  },
  {
    "title": "Régimen Contributivo",
    "href": "/afiliados/contributivo",
    "keywords": ["contributivo", "trabajadores", "independientes", "aporte"],
    "icon": "HeartHandshake"
  },
  {
    "title": "Blog y Noticias",
    "href": "/blog",
    "keywords": ["blog", "noticias", "articulos", "novedades"],
    "icon": "Newspaper"
  },
  {
    "title": "Normatividad",
    "href": "/normatividad",
    "keywords": ["normatividad", "leyes", "decretos", "resoluciones"],
    "icon": "Book"
  },
  {
    "title": "Colaboradores",
    "href": "/colaboradores",
    "keywords": ["colaboradores", "equipo", "trabajo", "personal"],
    "icon": "Users"
  },
  {
    "title": "Información Pública",
    "href": "#",
    "keywords": ["transparencia", "acceso", "informacion", "publica"],
    "icon": "File"
  }
];
